use_frameworks!

target 'CastorSDK_Example' do
  pod 'CastorSDK', :path => '../'

  target 'CastorSDK_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.10'
  pod 'Nimble', '~> 5.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
